language: php

sudo: false

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly

install:
  - composer self-update
  - composer update --prefer-source

script:
  - ./vendor/bin/phpunit --configuration phpunit.xml

